name: clarity_web
description: "Integration with Microsoft Clarity Analytics in Flutter Web Application."
version: 1.0.1
repository: https://github.com/rod-moraes/clarity_web
homepage: https://rodmoraes.com.br

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - web/js/clarity_web.js
